# Generated by generate_make_file_py.py
# Make file 'data/small_probe.png' from binary data there (optionally) and return binary data
from base64 import b64decode


def make_binary_file(name: str = None):
    data = b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAIAAAA7N+mxAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAG' \
    b'JJREFUeNpi/P//PwO5gAWIGRkZIRysBsFlMRWwwIWQFSEDuAZMBSy4LCHW2XjcjN9oqOY93HPhQi5fk4Ek/x7ujy5fISQu45jwWA' \
    b'XUCSexOo0Fl048FhJlM0HASEkiAQgwACNKJO8ummitAAAAAElFTkSuQmCC'
    if name:
        with open(name, 'wb') as f:
            f.write(b64decode(data))


if __name__ == '__main__':
    make_binary_file('data/small_probe.png')
